/* plugin.c generated by valac 0.16.0, the Vala compiler
 * generated from plugin.vala, do not modify */

/*
 * Copyright (C) 2011-2012 Simon Busch <morphis@gravedo.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <fsobasics.h>
#include <freesmartphone.h>
#include <fsoframework.h>
#include <gio/gio.h>


#define FSO_AUDIO_TYPE_SYSTEM_INTEGRATOR (fso_audio_system_integrator_get_type ())
#define FSO_AUDIO_SYSTEM_INTEGRATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_AUDIO_TYPE_SYSTEM_INTEGRATOR, FsoAudioSystemIntegrator))
#define FSO_AUDIO_SYSTEM_INTEGRATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_AUDIO_TYPE_SYSTEM_INTEGRATOR, FsoAudioSystemIntegratorClass))
#define FSO_AUDIO_IS_SYSTEM_INTEGRATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_AUDIO_TYPE_SYSTEM_INTEGRATOR))
#define FSO_AUDIO_IS_SYSTEM_INTEGRATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_AUDIO_TYPE_SYSTEM_INTEGRATOR))
#define FSO_AUDIO_SYSTEM_INTEGRATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_AUDIO_TYPE_SYSTEM_INTEGRATOR, FsoAudioSystemIntegratorClass))

typedef struct _FsoAudioSystemIntegrator FsoAudioSystemIntegrator;
typedef struct _FsoAudioSystemIntegratorClass FsoAudioSystemIntegratorClass;
typedef struct _FsoAudioSystemIntegratorPrivate FsoAudioSystemIntegratorPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _fso_audio_system_integrator_switchAudioModeData fso_audio_system_integrator_switchAudioModeData;
typedef struct _fso_audio_system_integrator_handleCallStatusData fso_audio_system_integrator_handleCallStatusData;
typedef struct _fso_audio_system_integrator_handleGSMServiceAppearingData fso_audio_system_integrator_handleGSMServiceAppearingData;
typedef struct _fso_audio_system_integrator_handleGSMServiceDisappearingData fso_audio_system_integrator_handleGSMServiceDisappearingData;
typedef struct _fso_audio_system_integrator_registerObjectsData fso_audio_system_integrator_registerObjectsData;

struct _FsoAudioSystemIntegrator {
	FsoFrameworkAbstractObject parent_instance;
	FsoAudioSystemIntegratorPrivate * priv;
};

struct _FsoAudioSystemIntegratorClass {
	FsoFrameworkAbstractObjectClass parent_class;
};

struct _FsoAudioSystemIntegratorPrivate {
	FreeSmartphoneGSMCall* call_service;
	FreeSmartphoneAudioManager* audiomanager_service;
	FsoFrameworkDBusServiceNotifier* service_notifier;
	gboolean ready;
};

struct _fso_audio_system_integrator_switchAudioModeData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoAudioSystemIntegrator* self;
	FreeSmartphoneAudioMode mode;
	FsoFrameworkLogger* _tmp0_;
	FreeSmartphoneAudioMode _tmp1_;
	GEnumValue* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gboolean _tmp5_;
	FreeSmartphoneAudioManager* _tmp6_;
	FreeSmartphoneAudioMode _tmp7_;
	GError* _error_;
	FsoFrameworkLogger* _tmp8_;
	FreeSmartphoneAudioMode _tmp9_;
	GEnumValue* _tmp10_;
	GError* _tmp11_;
	const gchar* _tmp12_;
	const gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	GError * _inner_error_;
};

struct _fso_audio_system_integrator_handleCallStatusData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoAudioSystemIntegrator* self;
	FreeSmartphoneGSMCallStatus status;
	gboolean _tmp0_;
	FsoFrameworkLogger* _tmp1_;
	FreeSmartphoneGSMCallStatus _tmp2_;
	GEnumValue* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	FsoFrameworkLogger* _tmp6_;
	FreeSmartphoneGSMCallStatus _tmp7_;
	GEnumValue* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gboolean _tmp11_;
	FreeSmartphoneGSMCallStatus _tmp12_;
};

struct _fso_audio_system_integrator_handleGSMServiceAppearingData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoAudioSystemIntegrator* self;
	gchar* busname;
	const gchar* _tmp0_;
	FreeSmartphoneGSMCall* _tmp1_;
	FreeSmartphoneGSMCall* _tmp2_;
	FreeSmartphoneGSMCall* _tmp3_;
	GError* _error_;
	FsoFrameworkLogger* _tmp4_;
	GError* _tmp5_;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	FreeSmartphoneGSMCall* _tmp10_;
	GError * _inner_error_;
};

struct _fso_audio_system_integrator_handleGSMServiceDisappearingData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoAudioSystemIntegrator* self;
	gchar* busname;
	const gchar* _tmp0_;
};

struct _fso_audio_system_integrator_registerObjectsData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	FsoAudioSystemIntegrator* self;
	FsoFrameworkLogger* _tmp0_;
	gboolean _tmp1_;
	FreeSmartphoneAudioManager* _tmp2_;
	FreeSmartphoneAudioManager* _tmp3_;
	FreeSmartphoneGSMCall* _tmp4_;
	FreeSmartphoneGSMCall* _tmp5_;
	FreeSmartphoneGSMCall* _tmp6_;
	FsoFrameworkDBusServiceNotifier* _tmp7_;
	FsoFrameworkDBusServiceNotifier* _tmp8_;
	FreeSmartphoneGSMCall* _tmp9_;
	gboolean _tmp10_;
	FsoFrameworkLogger* _tmp11_;
	gboolean _tmp12_;
	GError* _error_;
	FsoFrameworkLogger* _tmp13_;
	GError* _tmp14_;
	const gchar* _tmp15_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	GError * _inner_error_;
};


static gpointer fso_audio_system_integrator_parent_class = NULL;
static GType fso_audio_system_integrator_type_id = 0;
extern FsoAudioSystemIntegrator* instance;
FsoAudioSystemIntegrator* instance = NULL;

#define FSO_AUDIO_SYSTEM_INTEGRATION_MODULE_NAME "fsoaudio.system_integration"
GType fso_audio_system_integrator_get_type (void) G_GNUC_CONST;
GType fso_audio_system_integrator_register_type (GTypeModule * module);
#define FSO_AUDIO_SYSTEM_INTEGRATOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FSO_AUDIO_TYPE_SYSTEM_INTEGRATOR, FsoAudioSystemIntegratorPrivate))
enum  {
	FSO_AUDIO_SYSTEM_INTEGRATOR_DUMMY_PROPERTY
};
FsoAudioSystemIntegrator* fso_audio_system_integrator_new (void);
FsoAudioSystemIntegrator* fso_audio_system_integrator_construct (GType object_type);
static gboolean __lambda2_ (FsoAudioSystemIntegrator* self);
static void fso_audio_system_integrator_registerObjects (FsoAudioSystemIntegrator* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void fso_audio_system_integrator_registerObjects_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_);
static gboolean ___lambda2__gsource_func (gpointer self);
static gchar* fso_audio_system_integrator_real_repr (FsoFrameworkAbstractObject* base);
static void fso_audio_system_integrator_switchAudioMode_data_free (gpointer _data);
static void fso_audio_system_integrator_switchAudioMode (FsoAudioSystemIntegrator* self, FreeSmartphoneAudioMode mode, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void fso_audio_system_integrator_switchAudioMode_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_);
static gboolean fso_audio_system_integrator_switchAudioMode_co (fso_audio_system_integrator_switchAudioModeData* _data_);
const gchar* free_smartphone_audio_mode_to_string (FreeSmartphoneAudioMode self);
static void fso_audio_system_integrator_switchAudioMode_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void fso_audio_system_integrator_handleCallStatus_data_free (gpointer _data);
static void fso_audio_system_integrator_handleCallStatus (FsoAudioSystemIntegrator* self, FreeSmartphoneGSMCallStatus status, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void fso_audio_system_integrator_handleCallStatus_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_);
static gboolean fso_audio_system_integrator_handleCallStatus_co (fso_audio_system_integrator_handleCallStatusData* _data_);
const gchar* free_smartphone_gsm_call_status_to_string (FreeSmartphoneGSMCallStatus self);
static void fso_audio_system_integrator_handleGSMServiceAppearing_data_free (gpointer _data);
static void fso_audio_system_integrator_handleGSMServiceAppearing (FsoAudioSystemIntegrator* self, const gchar* busname, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void fso_audio_system_integrator_handleGSMServiceAppearing_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_);
static gboolean fso_audio_system_integrator_handleGSMServiceAppearing_co (fso_audio_system_integrator_handleGSMServiceAppearingData* _data_);
static void fso_audio_system_integrator_handleGSMServiceAppearing_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void ___lambda5_ (FsoAudioSystemIntegrator* self, gint id, FreeSmartphoneGSMCallStatus status, GHashTable* properties);
static void ____lambda5__free_smartphone_gsm_call_call_status (FreeSmartphoneGSMCall* _sender, gint id, FreeSmartphoneGSMCallStatus status, GHashTable* properties, gpointer self);
static void fso_audio_system_integrator_handleGSMServiceDisappearing_data_free (gpointer _data);
static void fso_audio_system_integrator_handleGSMServiceDisappearing (FsoAudioSystemIntegrator* self, const gchar* busname, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void fso_audio_system_integrator_handleGSMServiceDisappearing_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_);
static gboolean fso_audio_system_integrator_handleGSMServiceDisappearing_co (fso_audio_system_integrator_handleGSMServiceDisappearingData* _data_);
static void fso_audio_system_integrator_registerObjects_data_free (gpointer _data);
static gboolean fso_audio_system_integrator_registerObjects_co (fso_audio_system_integrator_registerObjectsData* _data_);
static void fso_audio_system_integrator_registerObjects_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void ___lambda3_ (FsoAudioSystemIntegrator* self, gint id, FreeSmartphoneGSMCallStatus status, GHashTable* properties);
static void ____lambda3__free_smartphone_gsm_call_call_status (FreeSmartphoneGSMCall* _sender, gint id, FreeSmartphoneGSMCallStatus status, GHashTable* properties, gpointer self);
static void ___lambda4_ (FsoAudioSystemIntegrator* self, const gchar* busname);
static void ____lambda4__fso_framework_dbus_service_event_func (const gchar* busname, gpointer self);
static void ___lambda6_ (FsoAudioSystemIntegrator* self, const gchar* busname);
static void ____lambda6__fso_framework_dbus_service_event_func (const gchar* busname, gpointer self);
static void fso_audio_system_integrator_finalize (GObject* obj);
gchar* fso_factory_function (FsoFrameworkSubsystem* subsystem, GError** error);
void fso_register_function (GTypeModule* module);


static gboolean __lambda2_ (FsoAudioSystemIntegrator* self) {
	gboolean result = FALSE;
	fso_audio_system_integrator_registerObjects (self, NULL, NULL);
	result = FALSE;
	return result;
}


static gboolean ___lambda2__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda2_ (self);
	return result;
}


FsoAudioSystemIntegrator* fso_audio_system_integrator_construct (GType object_type) {
	FsoAudioSystemIntegrator * self = NULL;
	FsoFrameworkDBusServiceNotifier* _tmp0_;
	self = (FsoAudioSystemIntegrator*) fso_framework_abstract_object_construct (object_type);
	self->priv->ready = FALSE;
	_tmp0_ = fso_framework_dbus_service_notifier_new ();
	_g_object_unref0 (self->priv->service_notifier);
	self->priv->service_notifier = _tmp0_;
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ___lambda2__gsource_func, g_object_ref (self), g_object_unref);
	return self;
}


FsoAudioSystemIntegrator* fso_audio_system_integrator_new (void) {
	return fso_audio_system_integrator_construct (FSO_AUDIO_TYPE_SYSTEM_INTEGRATOR);
}


static gchar* fso_audio_system_integrator_real_repr (FsoFrameworkAbstractObject* base) {
	FsoAudioSystemIntegrator * self;
	gchar* result = NULL;
	gchar* _tmp0_;
	self = (FsoAudioSystemIntegrator*) base;
	_tmp0_ = g_strdup ("<>");
	result = _tmp0_;
	return result;
}


static void fso_audio_system_integrator_switchAudioMode_data_free (gpointer _data) {
	fso_audio_system_integrator_switchAudioModeData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_audio_system_integrator_switchAudioModeData, _data_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void fso_audio_system_integrator_switchAudioMode (FsoAudioSystemIntegrator* self, FreeSmartphoneAudioMode mode, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	fso_audio_system_integrator_switchAudioModeData* _data_;
	FsoAudioSystemIntegrator* _tmp0_;
	FreeSmartphoneAudioMode _tmp1_;
	_data_ = g_slice_new0 (fso_audio_system_integrator_switchAudioModeData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_audio_system_integrator_switchAudioMode);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_audio_system_integrator_switchAudioMode_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = mode;
	_data_->mode = _tmp1_;
	fso_audio_system_integrator_switchAudioMode_co (_data_);
}


static void fso_audio_system_integrator_switchAudioMode_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_) {
	fso_audio_system_integrator_switchAudioModeData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void fso_audio_system_integrator_switchAudioMode_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	fso_audio_system_integrator_switchAudioModeData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_audio_system_integrator_switchAudioMode_co (_data_);
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static gboolean fso_audio_system_integrator_switchAudioMode_co (fso_audio_system_integrator_switchAudioModeData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
	_data_->_tmp1_ = _data_->mode;
	_data_->_tmp2_ = g_enum_get_value (g_type_class_ref (FREE_SMARTPHONE_AUDIO_TYPE_MODE), _data_->_tmp1_);
	_data_->_tmp3_ = NULL;
	_data_->_tmp3_ = g_strconcat ("Switching audio mode to ", (_data_->_tmp2_ != NULL) ? _data_->_tmp2_->value_name : NULL, NULL);
	_data_->_tmp4_ = _data_->_tmp3_;
	_data_->_tmp5_ = FALSE;
	_data_->_tmp5_ = fso_framework_logger_debug (_data_->_tmp0_, _data_->_tmp4_);
	g_assert (_data_->_tmp5_);
	_g_free0 (_data_->_tmp4_);
	{
		_data_->_tmp6_ = _data_->self->priv->audiomanager_service;
		_data_->_tmp7_ = _data_->mode;
		_data_->_state_ = 1;
		free_smartphone_audio_manager_set_mode (_data_->_tmp6_, _data_->_tmp7_, fso_audio_system_integrator_switchAudioMode_ready, _data_);
		return FALSE;
		_state_1:
		free_smartphone_audio_manager_set_mode_finish (_data_->_tmp6_, _data_->_res_, &_data_->_inner_error_);
		if (_data_->_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		_data_->_error_ = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		_data_->_tmp8_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		_data_->_tmp9_ = _data_->mode;
		_data_->_tmp10_ = g_enum_get_value (g_type_class_ref (FREE_SMARTPHONE_AUDIO_TYPE_MODE), _data_->_tmp9_);
		_data_->_tmp11_ = _data_->_error_;
		_data_->_tmp12_ = _data_->_tmp11_->message;
		_data_->_tmp13_ = NULL;
		_data_->_tmp13_ = string_to_string (_data_->_tmp12_);
		_data_->_tmp14_ = NULL;
		_data_->_tmp14_ = g_strconcat ("Could not set audio mode to ", (_data_->_tmp10_ != NULL) ? _data_->_tmp10_->value_name : NULL, ": ", _data_->_tmp13_, NULL);
		_data_->_tmp15_ = _data_->_tmp14_;
		fso_framework_logger_error (_data_->_tmp8_, _data_->_tmp15_);
		_g_free0 (_data_->_tmp15_);
		_g_error_free0 (_data_->_error_);
	}
	__finally0:
	if (_data_->_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_audio_system_integrator_handleCallStatus_data_free (gpointer _data) {
	fso_audio_system_integrator_handleCallStatusData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_audio_system_integrator_handleCallStatusData, _data_);
}


static void fso_audio_system_integrator_handleCallStatus (FsoAudioSystemIntegrator* self, FreeSmartphoneGSMCallStatus status, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	fso_audio_system_integrator_handleCallStatusData* _data_;
	FsoAudioSystemIntegrator* _tmp0_;
	FreeSmartphoneGSMCallStatus _tmp1_;
	_data_ = g_slice_new0 (fso_audio_system_integrator_handleCallStatusData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_audio_system_integrator_handleCallStatus);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_audio_system_integrator_handleCallStatus_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = status;
	_data_->status = _tmp1_;
	fso_audio_system_integrator_handleCallStatus_co (_data_);
}


static void fso_audio_system_integrator_handleCallStatus_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_) {
	fso_audio_system_integrator_handleCallStatusData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


/**
         * When the status of call switches to active or release we need to set the audio
         * mode according to this.
         **/
static gboolean fso_audio_system_integrator_handleCallStatus_co (fso_audio_system_integrator_handleCallStatusData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->ready;
	if (!_data_->_tmp0_) {
		_data_->_tmp1_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		_data_->_tmp2_ = _data_->status;
		_data_->_tmp3_ = g_enum_get_value (g_type_class_ref (FREE_SMARTPHONE_GSM_TYPE_CALL_STATUS), _data_->_tmp2_);
		_data_->_tmp4_ = NULL;
		_data_->_tmp4_ = g_strconcat ("Not yet ready to handle call status ", (_data_->_tmp3_ != NULL) ? _data_->_tmp3_->value_name : NULL, NULL);
		_data_->_tmp5_ = _data_->_tmp4_;
		fso_framework_logger_warning (_data_->_tmp1_, _data_->_tmp5_);
		_g_free0 (_data_->_tmp5_);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->_tmp6_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
	_data_->_tmp7_ = _data_->status;
	_data_->_tmp8_ = g_enum_get_value (g_type_class_ref (FREE_SMARTPHONE_GSM_TYPE_CALL_STATUS), _data_->_tmp7_);
	_data_->_tmp9_ = NULL;
	_data_->_tmp9_ = g_strconcat ("Got call status ", (_data_->_tmp8_ != NULL) ? _data_->_tmp8_->value_name : NULL, NULL);
	_data_->_tmp10_ = _data_->_tmp9_;
	_data_->_tmp11_ = FALSE;
	_data_->_tmp11_ = fso_framework_logger_debug (_data_->_tmp6_, _data_->_tmp10_);
	g_assert (_data_->_tmp11_);
	_g_free0 (_data_->_tmp10_);
	_data_->_tmp12_ = _data_->status;
	switch (_data_->_tmp12_) {
		case FREE_SMARTPHONE_GSM_CALL_STATUS_OUTGOING:
		case FREE_SMARTPHONE_GSM_CALL_STATUS_ACTIVE:
		{
			fso_audio_system_integrator_switchAudioMode (_data_->self, FREE_SMARTPHONE_AUDIO_MODE_CALL, NULL, NULL);
			break;
		}
		case FREE_SMARTPHONE_GSM_CALL_STATUS_RELEASE:
		{
			fso_audio_system_integrator_switchAudioMode (_data_->self, FREE_SMARTPHONE_AUDIO_MODE_NORMAL, NULL, NULL);
			break;
		}
		default:
		break;
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_audio_system_integrator_handleGSMServiceAppearing_data_free (gpointer _data) {
	fso_audio_system_integrator_handleGSMServiceAppearingData* _data_;
	_data_ = _data;
	_g_free0 (_data_->busname);
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_audio_system_integrator_handleGSMServiceAppearingData, _data_);
}


static void fso_audio_system_integrator_handleGSMServiceAppearing (FsoAudioSystemIntegrator* self, const gchar* busname, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	fso_audio_system_integrator_handleGSMServiceAppearingData* _data_;
	FsoAudioSystemIntegrator* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	_data_ = g_slice_new0 (fso_audio_system_integrator_handleGSMServiceAppearingData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_audio_system_integrator_handleGSMServiceAppearing);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_audio_system_integrator_handleGSMServiceAppearing_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = busname;
	_tmp2_ = g_strdup (_tmp1_);
	_data_->busname = _tmp2_;
	fso_audio_system_integrator_handleGSMServiceAppearing_co (_data_);
}


static void fso_audio_system_integrator_handleGSMServiceAppearing_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_) {
	fso_audio_system_integrator_handleGSMServiceAppearingData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void fso_audio_system_integrator_handleGSMServiceAppearing_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	fso_audio_system_integrator_handleGSMServiceAppearingData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_audio_system_integrator_handleGSMServiceAppearing_co (_data_);
}


static void ___lambda5_ (FsoAudioSystemIntegrator* self, gint id, FreeSmartphoneGSMCallStatus status, GHashTable* properties) {
	FreeSmartphoneGSMCallStatus _tmp0_;
	g_return_if_fail (properties != NULL);
	_tmp0_ = status;
	fso_audio_system_integrator_handleCallStatus (self, _tmp0_, NULL, NULL);
}


static void ____lambda5__free_smartphone_gsm_call_call_status (FreeSmartphoneGSMCall* _sender, gint id, FreeSmartphoneGSMCallStatus status, GHashTable* properties, gpointer self) {
	___lambda5_ (self, id, status, properties);
}


static gboolean fso_audio_system_integrator_handleGSMServiceAppearing_co (fso_audio_system_integrator_handleGSMServiceAppearingData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->busname;
	if (g_strcmp0 (_data_->_tmp0_, "org.freesmartphone.ogsmd") != 0) {
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	{
		_data_->_state_ = 1;
		g_async_initable_new_async (FREE_SMARTPHONE_GSM_TYPE_CALL_PROXY, 0, NULL, fso_audio_system_integrator_handleGSMServiceAppearing_ready, _data_, "g-flags", G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START, "g-name", "org.freesmartphone.ogsmd", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", "/org/freesmartphone/GSM/Device", "g-interface-name", "org.freesmartphone.GSM.Call", NULL);
		return FALSE;
		_state_1:
		_data_->_tmp1_ = NULL;
		_data_->_tmp1_ = g_async_initable_new_finish (_data_->_source_object_, _data_->_res_, &_data_->_inner_error_);
		_data_->_tmp2_ = (FreeSmartphoneGSMCall*) _data_->_tmp1_;
		if (_data_->_inner_error_ != NULL) {
			goto __catch1_g_error;
		}
		_g_object_unref0 (_data_->self->priv->call_service);
		_data_->self->priv->call_service = _data_->_tmp2_;
		_data_->_tmp3_ = _data_->self->priv->call_service;
		g_signal_connect_object (_data_->_tmp3_, "call-status", (GCallback) ____lambda5__free_smartphone_gsm_call_call_status, _data_->self, 0);
	}
	goto __finally1;
	__catch1_g_error:
	{
		_data_->_error_ = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		_data_->_tmp4_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		_data_->_tmp5_ = _data_->_error_;
		_data_->_tmp6_ = _data_->_tmp5_->message;
		_data_->_tmp7_ = NULL;
		_data_->_tmp7_ = string_to_string (_data_->_tmp6_);
		_data_->_tmp8_ = NULL;
		_data_->_tmp8_ = g_strconcat ("Could not get proxy object for call service: ", _data_->_tmp7_, NULL);
		_data_->_tmp9_ = _data_->_tmp8_;
		fso_framework_logger_error (_data_->_tmp4_, _data_->_tmp9_);
		_g_free0 (_data_->_tmp9_);
		_g_error_free0 (_data_->_error_);
	}
	__finally1:
	if (_data_->_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	_data_->_tmp10_ = _data_->self->priv->call_service;
	_data_->self->priv->ready = _data_->_tmp10_ != NULL;
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_audio_system_integrator_handleGSMServiceDisappearing_data_free (gpointer _data) {
	fso_audio_system_integrator_handleGSMServiceDisappearingData* _data_;
	_data_ = _data;
	_g_free0 (_data_->busname);
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_audio_system_integrator_handleGSMServiceDisappearingData, _data_);
}


static void fso_audio_system_integrator_handleGSMServiceDisappearing (FsoAudioSystemIntegrator* self, const gchar* busname, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	fso_audio_system_integrator_handleGSMServiceDisappearingData* _data_;
	FsoAudioSystemIntegrator* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	_data_ = g_slice_new0 (fso_audio_system_integrator_handleGSMServiceDisappearingData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_audio_system_integrator_handleGSMServiceDisappearing);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_audio_system_integrator_handleGSMServiceDisappearing_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = busname;
	_tmp2_ = g_strdup (_tmp1_);
	_data_->busname = _tmp2_;
	fso_audio_system_integrator_handleGSMServiceDisappearing_co (_data_);
}


static void fso_audio_system_integrator_handleGSMServiceDisappearing_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_) {
	fso_audio_system_integrator_handleGSMServiceDisappearingData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean fso_audio_system_integrator_handleGSMServiceDisappearing_co (fso_audio_system_integrator_handleGSMServiceDisappearingData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->busname;
	if (g_strcmp0 (_data_->_tmp0_, "org.freesmartphone.ogsmd") != 0) {
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_g_object_unref0 (_data_->self->priv->call_service);
	_data_->self->priv->call_service = NULL;
	_data_->self->priv->ready = FALSE;
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_audio_system_integrator_registerObjects_data_free (gpointer _data) {
	fso_audio_system_integrator_registerObjectsData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (fso_audio_system_integrator_registerObjectsData, _data_);
}


static void fso_audio_system_integrator_registerObjects (FsoAudioSystemIntegrator* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	fso_audio_system_integrator_registerObjectsData* _data_;
	FsoAudioSystemIntegrator* _tmp0_;
	_data_ = g_slice_new0 (fso_audio_system_integrator_registerObjectsData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, fso_audio_system_integrator_registerObjects);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, fso_audio_system_integrator_registerObjects_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	fso_audio_system_integrator_registerObjects_co (_data_);
}


static void fso_audio_system_integrator_registerObjects_finish (FsoAudioSystemIntegrator* self, GAsyncResult* _res_) {
	fso_audio_system_integrator_registerObjectsData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void fso_audio_system_integrator_registerObjects_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	fso_audio_system_integrator_registerObjectsData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	fso_audio_system_integrator_registerObjects_co (_data_);
}


static void ___lambda3_ (FsoAudioSystemIntegrator* self, gint id, FreeSmartphoneGSMCallStatus status, GHashTable* properties) {
	FreeSmartphoneGSMCallStatus _tmp0_;
	g_return_if_fail (properties != NULL);
	_tmp0_ = status;
	fso_audio_system_integrator_handleCallStatus (self, _tmp0_, NULL, NULL);
}


static void ____lambda3__free_smartphone_gsm_call_call_status (FreeSmartphoneGSMCall* _sender, gint id, FreeSmartphoneGSMCallStatus status, GHashTable* properties, gpointer self) {
	___lambda3_ (self, id, status, properties);
}


static void ___lambda4_ (FsoAudioSystemIntegrator* self, const gchar* busname) {
	const gchar* _tmp0_;
	g_return_if_fail (busname != NULL);
	_tmp0_ = busname;
	fso_audio_system_integrator_handleGSMServiceAppearing (self, _tmp0_, NULL, NULL);
}


static void ____lambda4__fso_framework_dbus_service_event_func (const gchar* busname, gpointer self) {
	___lambda4_ (self, busname);
}


static void ___lambda6_ (FsoAudioSystemIntegrator* self, const gchar* busname) {
	const gchar* _tmp0_;
	g_return_if_fail (busname != NULL);
	_tmp0_ = busname;
	fso_audio_system_integrator_handleGSMServiceDisappearing (self, _tmp0_, NULL, NULL);
}


static void ____lambda6__fso_framework_dbus_service_event_func (const gchar* busname, gpointer self) {
	___lambda6_ (self, busname);
}


static gboolean fso_audio_system_integrator_registerObjects_co (fso_audio_system_integrator_registerObjectsData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		case 2:
		goto _state_2;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	{
		_data_->_tmp0_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		_data_->_tmp1_ = FALSE;
		_data_->_tmp1_ = fso_framework_logger_debug (_data_->_tmp0_, "Started registration process with call service ...");
		g_assert (_data_->_tmp1_);
		_data_->_state_ = 1;
		g_async_initable_new_async (FREE_SMARTPHONE_AUDIO_TYPE_MANAGER_PROXY, 0, NULL, fso_audio_system_integrator_registerObjects_ready, _data_, "g-flags", G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START, "g-name", "org.freesmartphone.oaudiod", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", "/org/freesmartphone/Audio", "g-interface-name", "org.freesmartphone.Audio.Manager", NULL);
		return FALSE;
		_state_1:
		_data_->_tmp2_ = NULL;
		_data_->_tmp2_ = g_async_initable_new_finish (_data_->_source_object_, _data_->_res_, &_data_->_inner_error_);
		_data_->_tmp3_ = (FreeSmartphoneAudioManager*) _data_->_tmp2_;
		if (_data_->_inner_error_ != NULL) {
			goto __catch2_g_error;
		}
		_g_object_unref0 (_data_->self->priv->audiomanager_service);
		_data_->self->priv->audiomanager_service = _data_->_tmp3_;
		_data_->_state_ = 2;
		g_async_initable_new_async (FREE_SMARTPHONE_GSM_TYPE_CALL_PROXY, 0, NULL, fso_audio_system_integrator_registerObjects_ready, _data_, "g-flags", G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START, "g-name", "org.freesmartphone.ogsmd", "g-bus-type", G_BUS_TYPE_SYSTEM, "g-object-path", "/org/freesmartphone/GSM/Device", "g-interface-name", "org.freesmartphone.GSM.Call", NULL);
		return FALSE;
		_state_2:
		_data_->_tmp4_ = NULL;
		_data_->_tmp4_ = g_async_initable_new_finish (_data_->_source_object_, _data_->_res_, &_data_->_inner_error_);
		_data_->_tmp5_ = (FreeSmartphoneGSMCall*) _data_->_tmp4_;
		if (_data_->_inner_error_ != NULL) {
			goto __catch2_g_error;
		}
		_g_object_unref0 (_data_->self->priv->call_service);
		_data_->self->priv->call_service = _data_->_tmp5_;
		_data_->_tmp6_ = _data_->self->priv->call_service;
		g_signal_connect_object (_data_->_tmp6_, "call-status", (GCallback) ____lambda3__free_smartphone_gsm_call_call_status, _data_->self, 0);
		_data_->_tmp7_ = _data_->self->priv->service_notifier;
		fso_framework_dbus_service_notifier_notifyAppearing (_data_->_tmp7_, "org.freesmartphone.ogsmd", ____lambda4__fso_framework_dbus_service_event_func, _data_->self);
		_data_->_tmp8_ = _data_->self->priv->service_notifier;
		fso_framework_dbus_service_notifier_notifyDisappearing (_data_->_tmp8_, "org.freesmartphone.ogsmd", ____lambda6__fso_framework_dbus_service_event_func, _data_->self);
		_data_->_tmp9_ = _data_->self->priv->call_service;
		_data_->self->priv->ready = _data_->_tmp9_ != NULL;
		_data_->_tmp10_ = _data_->self->priv->ready;
		if (_data_->_tmp10_) {
			_data_->_tmp11_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
			_data_->_tmp12_ = FALSE;
			_data_->_tmp12_ = fso_framework_logger_debug (_data_->_tmp11_, "Successfully registered with call service!");
			g_assert (_data_->_tmp12_);
		}
	}
	goto __finally2;
	__catch2_g_error:
	{
		_data_->_error_ = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		_data_->_tmp13_ = ((FsoFrameworkAbstractObject*) _data_->self)->logger;
		_data_->_tmp14_ = _data_->_error_;
		_data_->_tmp15_ = _data_->_tmp14_->message;
		_data_->_tmp16_ = NULL;
		_data_->_tmp16_ = string_to_string (_data_->_tmp15_);
		_data_->_tmp17_ = NULL;
		_data_->_tmp17_ = g_strconcat ("Could not create dbus proxies for relevant interfaces: ", _data_->_tmp16_, NULL);
		_data_->_tmp18_ = _data_->_tmp17_;
		fso_framework_logger_error (_data_->_tmp13_, _data_->_tmp18_);
		_g_free0 (_data_->_tmp18_);
		_g_error_free0 (_data_->_error_);
	}
	__finally2:
	if (_data_->_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void fso_audio_system_integrator_class_init (FsoAudioSystemIntegratorClass * klass) {
	fso_audio_system_integrator_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FsoAudioSystemIntegratorPrivate));
	FSO_FRAMEWORK_ABSTRACT_OBJECT_CLASS (klass)->repr = fso_audio_system_integrator_real_repr;
	G_OBJECT_CLASS (klass)->finalize = fso_audio_system_integrator_finalize;
}


static void fso_audio_system_integrator_instance_init (FsoAudioSystemIntegrator * self) {
	self->priv = FSO_AUDIO_SYSTEM_INTEGRATOR_GET_PRIVATE (self);
}


static void fso_audio_system_integrator_finalize (GObject* obj) {
	FsoAudioSystemIntegrator * self;
	self = FSO_AUDIO_SYSTEM_INTEGRATOR (obj);
	_g_object_unref0 (self->priv->call_service);
	_g_object_unref0 (self->priv->audiomanager_service);
	_g_object_unref0 (self->priv->service_notifier);
	G_OBJECT_CLASS (fso_audio_system_integrator_parent_class)->finalize (obj);
}


GType fso_audio_system_integrator_get_type (void) {
	return fso_audio_system_integrator_type_id;
}


GType fso_audio_system_integrator_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (FsoAudioSystemIntegratorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fso_audio_system_integrator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FsoAudioSystemIntegrator), 0, (GInstanceInitFunc) fso_audio_system_integrator_instance_init, NULL };
	fso_audio_system_integrator_type_id = g_type_module_register_type (module, FSO_FRAMEWORK_TYPE_ABSTRACT_OBJECT, "FsoAudioSystemIntegrator", &g_define_type_info, 0);
	return fso_audio_system_integrator_type_id;
}


/**
 * This function gets called on plugin initialization time.
 * @return the name of your plugin here
 * @note that it needs to be a name in the format <subsystem>.<plugin>
 * else your module will be unloaded immediately.
 **/
gchar* fso_factory_function (FsoFrameworkSubsystem* subsystem, GError** error) {
	gchar* result = NULL;
	FsoAudioSystemIntegrator* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (subsystem != NULL, NULL);
	_tmp0_ = fso_audio_system_integrator_new ();
	_g_object_unref0 (instance);
	instance = _tmp0_;
	_tmp1_ = g_strdup (FSO_AUDIO_SYSTEM_INTEGRATION_MODULE_NAME);
	result = _tmp1_;
	return result;
}


void fso_register_function (GTypeModule* module) {
	FsoFrameworkLogger* _tmp0_;
	g_return_if_fail (module != NULL);
	fso_audio_system_integrator_register_type (module);
	_tmp0_ = fso_framework_theLogger;
	fso_framework_logger_debug (_tmp0_, "fsoaudio.system_integration fso_register_function");
}



