/* plugin.c generated by valac 0.16.1, the Vala compiler
 * generated from plugin.vala, do not modify */

/*
 * Copyright (C) 2011-2012 Simon Busch <morphis@gravedo.de>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <fsobasics.h>
#include <freesmartphone.h>
#include <alsa/asoundlib.h>
#include <fsoaudio.h>
#include <fsoframework.h>


#define FSO_AUDIO_TYPE_ALSA_STREAM_DEVICE (fso_audio_alsa_stream_device_get_type ())
#define FSO_AUDIO_ALSA_STREAM_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_AUDIO_TYPE_ALSA_STREAM_DEVICE, FsoAudioAlsaStreamDevice))
#define FSO_AUDIO_ALSA_STREAM_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_AUDIO_TYPE_ALSA_STREAM_DEVICE, FsoAudioAlsaStreamDeviceClass))
#define FSO_AUDIO_IS_ALSA_STREAM_DEVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_AUDIO_TYPE_ALSA_STREAM_DEVICE))
#define FSO_AUDIO_IS_ALSA_STREAM_DEVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_AUDIO_TYPE_ALSA_STREAM_DEVICE))
#define FSO_AUDIO_ALSA_STREAM_DEVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_AUDIO_TYPE_ALSA_STREAM_DEVICE, FsoAudioAlsaStreamDeviceClass))

typedef struct _FsoAudioAlsaStreamDevice FsoAudioAlsaStreamDevice;
typedef struct _FsoAudioAlsaStreamDeviceClass FsoAudioAlsaStreamDeviceClass;
typedef struct _FsoAudioAlsaStreamDevicePrivate FsoAudioAlsaStreamDevicePrivate;
#define _0(var) ((var == NULL) ? NULL : (var = ( (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _snd_pcm_info_free0(var) ((var == NULL) ? NULL : (var = (snd_pcm_info_free (var), NULL)))

#define FSO_AUDIO_TYPE_STREAM_CONTROL_ALSA (fso_audio_stream_control_alsa_get_type ())
#define FSO_AUDIO_STREAM_CONTROL_ALSA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FSO_AUDIO_TYPE_STREAM_CONTROL_ALSA, FsoAudioStreamControlAlsa))
#define FSO_AUDIO_STREAM_CONTROL_ALSA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FSO_AUDIO_TYPE_STREAM_CONTROL_ALSA, FsoAudioStreamControlAlsaClass))
#define FSO_AUDIO_IS_STREAM_CONTROL_ALSA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FSO_AUDIO_TYPE_STREAM_CONTROL_ALSA))
#define FSO_AUDIO_IS_STREAM_CONTROL_ALSA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FSO_AUDIO_TYPE_STREAM_CONTROL_ALSA))
#define FSO_AUDIO_STREAM_CONTROL_ALSA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FSO_AUDIO_TYPE_STREAM_CONTROL_ALSA, FsoAudioStreamControlAlsaClass))

typedef struct _FsoAudioStreamControlAlsa FsoAudioStreamControlAlsa;
typedef struct _FsoAudioStreamControlAlsaClass FsoAudioStreamControlAlsaClass;
typedef struct _FsoAudioStreamControlAlsaPrivate FsoAudioStreamControlAlsaPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _FsoAudioAlsaStreamDevice {
	FsoFrameworkAbstractObject parent_instance;
	FsoAudioAlsaStreamDevicePrivate * priv;
};

struct _FsoAudioAlsaStreamDeviceClass {
	FsoFrameworkAbstractObjectClass parent_class;
};

struct _FsoAudioAlsaStreamDevicePrivate {
	FreeSmartphoneAudioStream stream;
	snd_pcm_t* device;
};

struct _FsoAudioStreamControlAlsa {
	FsoAudioAbstractStreamControl parent_instance;
	FsoAudioStreamControlAlsaPrivate * priv;
};

struct _FsoAudioStreamControlAlsaClass {
	FsoAudioAbstractStreamControlClass parent_class;
};

struct _FsoAudioStreamControlAlsaPrivate {
	FsoAudioAlsaStreamDevice** devices;
	gint devices_length1;
	gint _devices_size_;
};


static gpointer fso_audio_alsa_stream_device_parent_class = NULL;
static GType fso_audio_alsa_stream_device_type_id = 0;
static gpointer fso_audio_stream_control_alsa_parent_class = NULL;
static GType fso_audio_stream_control_alsa_type_id = 0;

#define FSO_AUDIO_STREAMCONTROL_ALSA_MODULE_NAME "fsoaudio.streamcontrol_alsa"
GType fso_audio_alsa_stream_device_get_type (void) G_GNUC_CONST;
GType fso_audio_alsa_stream_device_register_type (GTypeModule * module);
#define FSO_AUDIO_ALSA_STREAM_DEVICE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FSO_AUDIO_TYPE_ALSA_STREAM_DEVICE, FsoAudioAlsaStreamDevicePrivate))
enum  {
	FSO_AUDIO_ALSA_STREAM_DEVICE_DUMMY_PROPERTY
};
static gchar* fso_audio_alsa_stream_device_stream_to_device_name (FsoAudioAlsaStreamDevice* self, FreeSmartphoneAudioStream stream);
FsoAudioAlsaStreamDevice* fso_audio_alsa_stream_device_new (FreeSmartphoneAudioStream stream);
FsoAudioAlsaStreamDevice* fso_audio_alsa_stream_device_construct (GType object_type, FreeSmartphoneAudioStream stream);
gboolean fso_audio_alsa_stream_device_initialize (FsoAudioAlsaStreamDevice* self);
const gchar* free_smartphone_audio_stream_to_string (FreeSmartphoneAudioStream self);
void fso_audio_alsa_stream_device_release (FsoAudioAlsaStreamDevice* self);
static gchar* fso_audio_alsa_stream_device_real_repr (FsoFrameworkAbstractObject* base);
static void fso_audio_alsa_stream_device_finalize (GObject* obj);
GType fso_audio_stream_control_alsa_get_type (void) G_GNUC_CONST;
GType fso_audio_stream_control_alsa_register_type (GTypeModule * module);
#define FSO_AUDIO_STREAM_CONTROL_ALSA_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FSO_AUDIO_TYPE_STREAM_CONTROL_ALSA, FsoAudioStreamControlAlsaPrivate))
enum  {
	FSO_AUDIO_STREAM_CONTROL_ALSA_DUMMY_PROPERTY
};
static void fso_audio_stream_control_alsa_real_setup (FsoAudioAbstractStreamControl* base);
static void fso_audio_stream_control_alsa_real_set_mute (FsoAudioAbstractStreamControl* base, FreeSmartphoneAudioStream stream, gboolean mute);
static void fso_audio_stream_control_alsa_real_set_volume (FsoAudioAbstractStreamControl* base, FreeSmartphoneAudioStream stream, guint level);
static gboolean fso_audio_stream_control_alsa_real_get_mute (FsoAudioAbstractStreamControl* base, FreeSmartphoneAudioStream stream);
static guint fso_audio_stream_control_alsa_real_get_volume (FsoAudioAbstractStreamControl* base, FreeSmartphoneAudioStream stream);
FsoAudioStreamControlAlsa* fso_audio_stream_control_alsa_new (void);
FsoAudioStreamControlAlsa* fso_audio_stream_control_alsa_construct (GType object_type);
static void fso_audio_stream_control_alsa_finalize (GObject* obj);
gchar* fso_factory_function (FsoFrameworkSubsystem* subsystem, GError** error);
void fso_register_function (GTypeModule* module);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gchar* fso_audio_alsa_stream_device_stream_to_device_name (FsoAudioAlsaStreamDevice* self, FreeSmartphoneAudioStream stream) {
	gchar* result = NULL;
	gchar* _tmp0_;
	gchar* _result_;
	FreeSmartphoneAudioStream _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup ("<unknown>");
	_result_ = _tmp0_;
	_tmp1_ = stream;
	switch (_tmp1_) {
		case FREE_SMARTPHONE_AUDIO_STREAM_MEDIA:
		{
			gchar* _tmp2_;
			_tmp2_ = g_strdup ("media");
			_g_free0 (_result_);
			_result_ = _tmp2_;
			break;
		}
		case FREE_SMARTPHONE_AUDIO_STREAM_ALERT:
		{
			gchar* _tmp3_;
			_tmp3_ = g_strdup ("alert");
			_g_free0 (_result_);
			_result_ = _tmp3_;
			break;
		}
		case FREE_SMARTPHONE_AUDIO_STREAM_RINGTONE:
		{
			gchar* _tmp4_;
			_tmp4_ = g_strdup ("ringtone");
			_g_free0 (_result_);
			_result_ = _tmp4_;
			break;
		}
		case FREE_SMARTPHONE_AUDIO_STREAM_ALARM:
		{
			gchar* _tmp5_;
			_tmp5_ = g_strdup ("alarm");
			_g_free0 (_result_);
			_result_ = _tmp5_;
			break;
		}
		case FREE_SMARTPHONE_AUDIO_STREAM_NAVIGATION:
		{
			gchar* _tmp6_;
			_tmp6_ = g_strdup ("navigation");
			_g_free0 (_result_);
			_result_ = _tmp6_;
			break;
		}
		default:
		{
			break;
		}
	}
	result = _result_;
	return result;
}


FsoAudioAlsaStreamDevice* fso_audio_alsa_stream_device_construct (GType object_type, FreeSmartphoneAudioStream stream) {
	FsoAudioAlsaStreamDevice * self = NULL;
	FreeSmartphoneAudioStream _tmp0_;
	self = (FsoAudioAlsaStreamDevice*) fso_framework_abstract_object_construct (object_type);
	_tmp0_ = stream;
	self->priv->stream = _tmp0_;
	return self;
}


FsoAudioAlsaStreamDevice* fso_audio_alsa_stream_device_new (FreeSmartphoneAudioStream stream) {
	return fso_audio_alsa_stream_device_construct (FSO_AUDIO_TYPE_ALSA_STREAM_DEVICE, stream);
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


gboolean fso_audio_alsa_stream_device_initialize (FsoAudioAlsaStreamDevice* self) {
	gboolean result = FALSE;
	gchar* _tmp0_;
	gchar* error_message;
	FreeSmartphoneAudioStream _tmp1_;
	gchar* _tmp2_ = NULL;
	gchar* device_name;
	const gchar* _tmp3_;
	snd_pcm_t* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	gint rc;
	gint _tmp6_;
	snd_pcm_info_t* info = NULL;
	snd_pcm_info_t* _tmp17_ = NULL;
	snd_pcm_t* _tmp18_;
	snd_pcm_info_t* _tmp19_;
	FsoFrameworkLogger* _tmp20_;
	FreeSmartphoneAudioStream _tmp21_;
	GEnumValue* _tmp22_;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = g_strdup ("");
	error_message = _tmp0_;
	_tmp1_ = self->priv->stream;
	_tmp2_ = fso_audio_alsa_stream_device_stream_to_device_name (self, _tmp1_);
	device_name = _tmp2_;
	_tmp3_ = device_name;
	_tmp5_ = snd_pcm_open (&_tmp4_, _tmp3_, SND_PCM_STREAM_PLAYBACK, 0);
	_0 (self->priv->device);
	self->priv->device = _tmp4_;
	rc = _tmp5_;
	_tmp6_ = rc;
	if (_tmp6_ < 0) {
		gint _tmp7_;
		const gchar* _tmp8_ = NULL;
		gchar* _tmp9_;
		FsoFrameworkLogger* _tmp10_;
		FreeSmartphoneAudioStream _tmp11_;
		GEnumValue* _tmp12_;
		const gchar* _tmp13_;
		const gchar* _tmp14_ = NULL;
		gchar* _tmp15_ = NULL;
		gchar* _tmp16_;
		_tmp7_ = rc;
		_tmp8_ = snd_strerror (_tmp7_);
		_tmp9_ = g_strdup (_tmp8_);
		_g_free0 (error_message);
		error_message = _tmp9_;
		_tmp10_ = ((FsoFrameworkAbstractObject*) self)->logger;
		_tmp11_ = self->priv->stream;
		_tmp12_ = g_enum_get_value (g_type_class_ref (FREE_SMARTPHONE_AUDIO_TYPE_STREAM), _tmp11_);
		_tmp13_ = error_message;
		_tmp14_ = string_to_string (_tmp13_);
		_tmp15_ = g_strconcat ("Failed to initialize pcm device for stream ", (_tmp12_ != NULL) ? _tmp12_->value_name : NULL, ": ", _tmp14_, NULL);
		_tmp16_ = _tmp15_;
		fso_framework_logger_error (_tmp10_, _tmp16_);
		_g_free0 (_tmp16_);
		result = FALSE;
		_g_free0 (device_name);
		_g_free0 (error_message);
		return result;
	}
	snd_pcm_info_malloc (&_tmp17_);
	_snd_pcm_info_free0 (info);
	info = _tmp17_;
	_tmp18_ = self->priv->device;
	_tmp19_ = info;
	snd_pcm_info (_tmp18_, _tmp19_);
	_tmp20_ = ((FsoFrameworkAbstractObject*) self)->logger;
	_tmp21_ = self->priv->stream;
	_tmp22_ = g_enum_get_value (g_type_class_ref (FREE_SMARTPHONE_AUDIO_TYPE_STREAM), _tmp21_);
	_tmp23_ = g_strconcat ("Initialized PCM device for stream ", (_tmp22_ != NULL) ? _tmp22_->value_name : NULL, " successfully!", NULL);
	_tmp24_ = _tmp23_;
	fso_framework_logger_debug (_tmp20_, _tmp24_);
	_g_free0 (_tmp24_);
	result = TRUE;
	_snd_pcm_info_free0 (info);
	_g_free0 (device_name);
	_g_free0 (error_message);
	return result;
}


void fso_audio_alsa_stream_device_release (FsoAudioAlsaStreamDevice* self) {
	gchar* _tmp0_;
	gchar* error_message;
	gint rc;
	snd_pcm_t* _tmp1_;
	snd_pcm_t* _tmp3_;
	gint _tmp4_ = 0;
	gint _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup ("");
	error_message = _tmp0_;
	rc = 0;
	_tmp1_ = self->priv->device;
	if (_tmp1_ == NULL) {
		FsoFrameworkLogger* _tmp2_;
		_tmp2_ = ((FsoFrameworkAbstractObject*) self)->logger;
		fso_framework_logger_error (_tmp2_, "Can't close a not initialized device!");
		_g_free0 (error_message);
		return;
	}
	_tmp3_ = self->priv->device;
	_tmp4_ = snd_pcm_close (_tmp3_);
	rc = _tmp4_;
	_tmp5_ = rc;
	if (_tmp5_ < 0) {
		gint _tmp6_;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		FsoFrameworkLogger* _tmp9_;
		FreeSmartphoneAudioStream _tmp10_;
		GEnumValue* _tmp11_;
		const gchar* _tmp12_;
		const gchar* _tmp13_ = NULL;
		gchar* _tmp14_ = NULL;
		gchar* _tmp15_;
		_tmp6_ = rc;
		_tmp7_ = snd_strerror (_tmp6_);
		_tmp8_ = g_strdup (_tmp7_);
		_g_free0 (error_message);
		error_message = _tmp8_;
		_tmp9_ = ((FsoFrameworkAbstractObject*) self)->logger;
		_tmp10_ = self->priv->stream;
		_tmp11_ = g_enum_get_value (g_type_class_ref (FREE_SMARTPHONE_AUDIO_TYPE_STREAM), _tmp10_);
		_tmp12_ = error_message;
		_tmp13_ = string_to_string (_tmp12_);
		_tmp14_ = g_strconcat ("Can't close pcm device for stream ", (_tmp11_ != NULL) ? _tmp11_->value_name : NULL, ": ", _tmp13_, NULL);
		_tmp15_ = _tmp14_;
		fso_framework_logger_error (_tmp9_, _tmp15_);
		_g_free0 (_tmp15_);
		_g_free0 (error_message);
		return;
	}
	_g_free0 (error_message);
}


static gchar* fso_audio_alsa_stream_device_real_repr (FsoFrameworkAbstractObject* base) {
	FsoAudioAlsaStreamDevice * self;
	gchar* result = NULL;
	gchar* _tmp0_;
	self = (FsoAudioAlsaStreamDevice*) base;
	_tmp0_ = g_strdup ("<>");
	result = _tmp0_;
	return result;
}


static void fso_audio_alsa_stream_device_class_init (FsoAudioAlsaStreamDeviceClass * klass) {
	fso_audio_alsa_stream_device_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FsoAudioAlsaStreamDevicePrivate));
	FSO_FRAMEWORK_ABSTRACT_OBJECT_CLASS (klass)->repr = fso_audio_alsa_stream_device_real_repr;
	G_OBJECT_CLASS (klass)->finalize = fso_audio_alsa_stream_device_finalize;
}


static void fso_audio_alsa_stream_device_instance_init (FsoAudioAlsaStreamDevice * self) {
	self->priv = FSO_AUDIO_ALSA_STREAM_DEVICE_GET_PRIVATE (self);
}


static void fso_audio_alsa_stream_device_finalize (GObject* obj) {
	FsoAudioAlsaStreamDevice * self;
	self = FSO_AUDIO_ALSA_STREAM_DEVICE (obj);
	_0 (self->priv->device);
	G_OBJECT_CLASS (fso_audio_alsa_stream_device_parent_class)->finalize (obj);
}


GType fso_audio_alsa_stream_device_get_type (void) {
	return fso_audio_alsa_stream_device_type_id;
}


GType fso_audio_alsa_stream_device_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (FsoAudioAlsaStreamDeviceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fso_audio_alsa_stream_device_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FsoAudioAlsaStreamDevice), 0, (GInstanceInitFunc) fso_audio_alsa_stream_device_instance_init, NULL };
	fso_audio_alsa_stream_device_type_id = g_type_module_register_type (module, FSO_FRAMEWORK_TYPE_ABSTRACT_OBJECT, "FsoAudioAlsaStreamDevice", &g_define_type_info, 0);
	return fso_audio_alsa_stream_device_type_id;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void fso_audio_stream_control_alsa_real_setup (FsoAudioAbstractStreamControl* base) {
	FsoAudioStreamControlAlsa * self;
	FsoFrameworkLogger* _tmp0_;
	FsoAudioAlsaStreamDevice* _tmp1_;
	FsoAudioAlsaStreamDevice** _tmp2_ = NULL;
	FsoAudioAlsaStreamDevice** _tmp3_;
	gint _tmp3__length1;
	self = (FsoAudioStreamControlAlsa*) base;
	_tmp0_ = ((FsoFrameworkAbstractObject*) self)->logger;
	fso_framework_logger_debug (_tmp0_, "StreamControlAlsa::setup");
	_tmp1_ = fso_audio_alsa_stream_device_new (FREE_SMARTPHONE_AUDIO_STREAM_MEDIA);
	_tmp2_ = g_new0 (FsoAudioAlsaStreamDevice*, 1 + 1);
	_tmp2_[0] = _tmp1_;
	self->priv->devices = (_vala_array_free (self->priv->devices, self->priv->devices_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->devices = _tmp2_;
	self->priv->devices_length1 = 1;
	self->priv->_devices_size_ = self->priv->devices_length1;
	_tmp3_ = self->priv->devices;
	_tmp3__length1 = self->priv->devices_length1;
	{
		FsoAudioAlsaStreamDevice** device_collection = NULL;
		gint device_collection_length1 = 0;
		gint _device_collection_size_ = 0;
		gint device_it = 0;
		device_collection = _tmp3_;
		device_collection_length1 = _tmp3__length1;
		for (device_it = 0; device_it < _tmp3__length1; device_it = device_it + 1) {
			FsoAudioAlsaStreamDevice* _tmp4_;
			FsoAudioAlsaStreamDevice* device = NULL;
			_tmp4_ = _g_object_ref0 (device_collection[device_it]);
			device = _tmp4_;
			{
				FsoAudioAlsaStreamDevice* _tmp5_;
				_tmp5_ = device;
				fso_audio_alsa_stream_device_initialize (_tmp5_);
				_g_object_unref0 (device);
			}
		}
	}
}


static void fso_audio_stream_control_alsa_real_set_mute (FsoAudioAbstractStreamControl* base, FreeSmartphoneAudioStream stream, gboolean mute) {
	FsoAudioStreamControlAlsa * self;
	self = (FsoAudioStreamControlAlsa*) base;
}


static void fso_audio_stream_control_alsa_real_set_volume (FsoAudioAbstractStreamControl* base, FreeSmartphoneAudioStream stream, guint level) {
	FsoAudioStreamControlAlsa * self;
	self = (FsoAudioStreamControlAlsa*) base;
}


static gboolean fso_audio_stream_control_alsa_real_get_mute (FsoAudioAbstractStreamControl* base, FreeSmartphoneAudioStream stream) {
	FsoAudioStreamControlAlsa * self;
	gboolean result = FALSE;
	self = (FsoAudioStreamControlAlsa*) base;
	result = FALSE;
	return result;
}


static guint fso_audio_stream_control_alsa_real_get_volume (FsoAudioAbstractStreamControl* base, FreeSmartphoneAudioStream stream) {
	FsoAudioStreamControlAlsa * self;
	guint result = 0U;
	self = (FsoAudioStreamControlAlsa*) base;
	result = (guint) 100;
	return result;
}


FsoAudioStreamControlAlsa* fso_audio_stream_control_alsa_construct (GType object_type) {
	FsoAudioStreamControlAlsa * self = NULL;
	self = (FsoAudioStreamControlAlsa*) fso_audio_abstract_stream_control_construct (object_type);
	return self;
}


FsoAudioStreamControlAlsa* fso_audio_stream_control_alsa_new (void) {
	return fso_audio_stream_control_alsa_construct (FSO_AUDIO_TYPE_STREAM_CONTROL_ALSA);
}


static void fso_audio_stream_control_alsa_class_init (FsoAudioStreamControlAlsaClass * klass) {
	fso_audio_stream_control_alsa_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FsoAudioStreamControlAlsaPrivate));
	FSO_AUDIO_ABSTRACT_STREAM_CONTROL_CLASS (klass)->setup = fso_audio_stream_control_alsa_real_setup;
	FSO_AUDIO_ABSTRACT_STREAM_CONTROL_CLASS (klass)->set_mute = fso_audio_stream_control_alsa_real_set_mute;
	FSO_AUDIO_ABSTRACT_STREAM_CONTROL_CLASS (klass)->set_volume = fso_audio_stream_control_alsa_real_set_volume;
	FSO_AUDIO_ABSTRACT_STREAM_CONTROL_CLASS (klass)->get_mute = fso_audio_stream_control_alsa_real_get_mute;
	FSO_AUDIO_ABSTRACT_STREAM_CONTROL_CLASS (klass)->get_volume = fso_audio_stream_control_alsa_real_get_volume;
	G_OBJECT_CLASS (klass)->finalize = fso_audio_stream_control_alsa_finalize;
}


static void fso_audio_stream_control_alsa_instance_init (FsoAudioStreamControlAlsa * self) {
	self->priv = FSO_AUDIO_STREAM_CONTROL_ALSA_GET_PRIVATE (self);
}


static void fso_audio_stream_control_alsa_finalize (GObject* obj) {
	FsoAudioStreamControlAlsa * self;
	self = FSO_AUDIO_STREAM_CONTROL_ALSA (obj);
	self->priv->devices = (_vala_array_free (self->priv->devices, self->priv->devices_length1, (GDestroyNotify) g_object_unref), NULL);
	G_OBJECT_CLASS (fso_audio_stream_control_alsa_parent_class)->finalize (obj);
}


GType fso_audio_stream_control_alsa_get_type (void) {
	return fso_audio_stream_control_alsa_type_id;
}


GType fso_audio_stream_control_alsa_register_type (GTypeModule * module) {
	static const GTypeInfo g_define_type_info = { sizeof (FsoAudioStreamControlAlsaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) fso_audio_stream_control_alsa_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FsoAudioStreamControlAlsa), 0, (GInstanceInitFunc) fso_audio_stream_control_alsa_instance_init, NULL };
	fso_audio_stream_control_alsa_type_id = g_type_module_register_type (module, FSO_AUDIO_TYPE_ABSTRACT_STREAM_CONTROL, "FsoAudioStreamControlAlsa", &g_define_type_info, 0);
	return fso_audio_stream_control_alsa_type_id;
}


/**
 * This function gets called on plugin initialization time.
 * @return the name of your plugin here
 * @note that it needs to be a name in the format <subsystem>.<plugin>
 * else your module will be unloaded immediately.
 **/
gchar* fso_factory_function (FsoFrameworkSubsystem* subsystem, GError** error) {
	gchar* result = NULL;
	gchar* _tmp0_;
	g_return_val_if_fail (subsystem != NULL, NULL);
	_tmp0_ = g_strdup (FSO_AUDIO_STREAMCONTROL_ALSA_MODULE_NAME);
	result = _tmp0_;
	return result;
}


void fso_register_function (GTypeModule* module) {
	FsoFrameworkLogger* _tmp0_;
	g_return_if_fail (module != NULL);
	fso_audio_alsa_stream_device_register_type (module);
	fso_audio_stream_control_alsa_register_type (module);
	_tmp0_ = fso_framework_theLogger;
	fso_framework_logger_debug (_tmp0_, "fsoaudio.streamcontrol_alsa fso_register_function");
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



